name: Deploy Web Demo to GitHub Pages

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'ghwebdemo/**'
      - 'examples/egui_native/**'
      - '.github/workflows/deploy-web-demo.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Build WASM demos
      run: |
        # Build the LinOSS web demo
        cd ghwebdemo
        # Add WASM target
        rustup target add wasm32-unknown-unknown
        # Build with linoss features (full D-LinOSS functionality)
        wasm-pack build --target web --out-dir wasm --out-name linoss_web_demo --features linoss
        # Clean up unnecessary files
        cd wasm
        rm -f .gitignore package.json README.md
        echo "✅ WASM build completed successfully"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './ghwebdemo'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3